namespace League.API.Models
{
    public enum ChampionListTags
    {
        all,
        allytips,
        blurb,
        enemytips,
        format,
        image,
        info,
        keys,
        lore,
        partype,
        passive,
        recommended,
        skins,
        spells,
        stats,
        tags
    }

    public enum ChampionTags
    {
        all,
        allytips,
        blurb,
        enemytips,
        image,
        info,
        lore,
        partype,
        passive,
        recommended,
        skins,
        spells,
        stats,
        tags
    }

    public enum ItemTags
    {
        all,
        colloq,
        consumeOnFull,
        consumed,
        depth,
        effect,
        from,
        gold,
        groups,
        hideFromAll,
        image,
        inStore,
        into,
        maps,
        requiredChampion,
        sanitizedDescription,
        specialRecipe,
        stacks,
        stats,
        tags,
        tree
    }

    public enum SpellTags
    {
        all,
        cooldown,
        cooldownBurn,
        cost,
        costBurn,
        costType,
        effect,
        effectBurn,
        image,
        key,
        leveltip,
        maxrank,
        modes,
        range,
        rangeBurn,
        resource,
        sanitizedDescription,
        sanitizedTooltip,
        tooltip,
        vars
    }
}
